### ISSUE TITLE
Edit/Delete Property

### ISSUE THREAD

**Issue by krod02** [RequirementsProject/RealtorWebsiteProject#10]
## Requirement
The website should allow real estate agents to edit or delete property listings (REA-001).

## Tasks
- [ ] Develop property edit and delete functionality
- [ ] Integrate edit and delete functionality with database
- [ ] Test property edit and delete functionality
