### ISSUE TITLE
Secure Login

### ISSUE THREAD

**Issue by krod02** [RequirementsProject/RealtorWebsiteProject#14]
## Requirement
The website should provide a secure login for real estate agents (REA-001).
## Tasks

- [ ] Implement secure login system (e.g. two-factor authentication)
- [ ] Test login system for vulnerabilities
- [ ] Train real estate agents on login procedures

**Comment by krod02** [comment]
From Use Case: REA-001
https://github.com/RequirementsProject/RealtorWebsiteProject/blob/main/Use%20Cases.pdf
