### ISSUE TITLE
Manage Account Information

### ISSUE THREAD

**Issue by krod02** [RequirementsProject/RealtorWebsiteProject#15]
## Requirement
The website should provide a way for real estate agents to manage their account information.
##Tasks

- [ ] Develop account management functionality
- [ ] Integrate account management functionality with database
- [ ] Test account management functionality

**Comment by krod02** [comment]
From Use Case: REA-001
https://github.com/RequirementsProject/RealtorWebsiteProject/blob/main/Use%20Cases.pdf
