### ISSUE TITLE
Buyer Saving Property Info.

### ISSUE THREAD

**Issue by krod02** [RequirementsProject/RealtorWebsiteProject#16]
## Requirement
The website should provide a way for potential buyers to save property information (REA-002).
## Tasks

- [ ] Develop property save functionality
- [ ] Integrate property save functionality with database
- [ ] Test property save functionality

**Comment by krod02** [comment]
From Use Case: REA-002
https://github.com/RequirementsProject/RealtorWebsiteProject/blob/main/Use%20Cases.pdf
