### ISSUE TITLE
Receive Property Alerts

### ISSUE THREAD

**Issue by krod02** [RequirementsProject/RealtorWebsiteProject#17]
## Requirement
The website should provide a way for potential buyers to receive property alerts (REA-002).
## Tasks

- [ ] Develop property alert system (e.g. email notifications)
- [ ] Integrate alert system with website and database
- [ ] Test alert system

**Comment by krod02** [comment]
From Use Case: REA-002
https://github.com/RequirementsProject/RealtorWebsiteProject/blob/main/Use%20Cases.pdf
