### ISSUE TITLE
External Listing Services

### ISSUE THREAD

**Issue by krod02** [RequirementsProject/RealtorWebsiteProject#18]
## Requirement
The website should allow for easy integration with external listing services (REA-001).
## Tasks
- [ ] Identify external listing services to integrate with
- [ ] Develop integration system (e.g. API)
- [ ] Test integration with external listing services

**Comment by krod02** [comment]
From Use Case: REA-001
https://github.com/RequirementsProject/RealtorWebsiteProject/blob/main/Use%20Cases.pdf
