### ISSUE TITLE
Website Accessibilities

### ISSUE THREAD

**Issue by krod02** [RequirementsProject/RealtorWebsiteProject#20]
## Requirement
The website should be accessible to users with disabilities.
## Tasks

- [ ] Ensure website conforms to accessibility standards
- [ ] Provide alternative text for images and videos
- [ ] Test website accessibility with screen readers and other assistive technologies

**Comment by krod02** [comment]
From Use Cases: REA-001, REA-002 
https://github.com/RequirementsProject/RealtorWebsiteProject/blob/main/Use%20Cases.pdf
