### ISSUE TITLE
Saving of Properties 

### ISSUE THREAD

**Issue by krod02** [RequirementsProject/RealtorWebsiteProject#9]
## Requirement
The website should allow real estate agents to save property information.
## Tasks

- [ ] Develop property save functionality
- [ ] Integrate property save functionality with database
- [ ] Test property save functionality

**Comment by krod02** [comment]
From Use Case: REA-002
https://github.com/RequirementsProject/RealtorWebsiteProject/blob/main/Use%20Cases.pdf
